spring:
  # 项目名称
  application:
    name: mall-fronted
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    # 全局日期格式
    date-format: yyyy-MM-dd
  servlet:
    # 上传文件限制
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MP 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台打印 SQL
    map-underscore-to-camel-case: false # 驼峰映射关闭
    cache-enabled: false # 使全局的映射器启用或禁用缓存
    lazy-loading-enabled: false # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    aggressive-lazy-loading: true # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# pageHelper 配置
pagehelper:
  helper-dialect: mysql # 指定分页数据库，不指定的话会默认自动检测数据库类型
  reasonable: true # 是否启用分页合理化，当 pagenum< 1 显示第一页，当 pagenum > pages 显示最后一页
  support-methods-arguments: true # 支持通过Mapper接口参数来传递分页参数，默认false
  params: count=countSql # POJO或者Map中发现了countSql属性，就会作为count参数使用
  returnPageInfo: check # always总是返回PageInfo类型,check检查返回类型是否为PageInfo,none返回Page
