spring:
  # 项目名称
  application:
    name: mall-fronted
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    # 全局日期格式
    date-format: yyyy-MM-dd
  servlet:
    # 上传文件限制
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MP 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false